package de.buxdehuda.archivar;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class SearchEditWindow extends javax.swing.JFrame {

    Archivar arch = new Archivar();
    Image rawImage, readyImage;
    Dimension rawDimension, readyDimension;
    boolean activeSearch = false;
    
    /**
     * Creates new form SearchEditWindow
     */
    public SearchEditWindow() {
        initComponents();
        //after event listeners:
        readyPicturesList.setSelectedIndex(0);
        rawPicturesList.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        tabWindow = new javax.swing.JTabbedPane();
        searchTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        readyPicturesList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        personsResultText = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        dateResultText = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        reasonResultText = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        placeResultText = new javax.swing.JTextPane();
        backButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        placeSearchField = new javax.swing.JTextField();
        dateSearchField = new javax.swing.JTextField();
        reasonSearchField = new javax.swing.JTextField();
        personsSearchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        coordinatesButton = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        openPictureButton = new javax.swing.JButton();
        readyPictureDisplayLabel = new javax.swing.JLabel();
        editTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rawPicturesList = new javax.swing.JList<>();
        personsTextField = new javax.swing.JTextField();
        reasonTextField = new javax.swing.JTextField();
        placeTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        openFolderButton = new javax.swing.JButton();
        rawPictureDisplayLabel = new javax.swing.JLabel();
        settingsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        saveSettings = new javax.swing.JButton();
        folderSetting = new javax.swing.JTextField();
        folderReadySetting = new javax.swing.JTextField();
        folderRawSetting = new javax.swing.JTextField();
        formatSetting = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        colorSetting = new javax.swing.JTextField();

        jScrollPane5.setViewportView(jTextPane3);

        jScrollPane7.setViewportView(jTextPane5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Archivar");
        setIconImage(new ImageIcon("src/res/icon.png").getImage());

        readyPicturesList.setModel(new ArrayListModel<>(arch.getReadyPictures()));
        readyPicturesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        readyPicturesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                readyPicturesListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(readyPicturesList);

        personsResultText.setEditable(false);
        personsResultText.setToolTipText("Personen");
        jScrollPane3.setViewportView(personsResultText);

        dateResultText.setEditable(false);
        dateResultText.setToolTipText("Datum");
        jScrollPane4.setViewportView(dateResultText);

        reasonResultText.setEditable(false);
        reasonResultText.setToolTipText("Anlass");
        jScrollPane6.setViewportView(reasonResultText);

        placeResultText.setEditable(false);
        placeResultText.setToolTipText("Ort");
        jScrollPane8.setViewportView(placeResultText);

        backButton.setText("◀");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        forwardButton.setText("▶");
        forwardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forwardButtonMouseClicked(evt);
            }
        });

        searchButton.setFont(searchButton.getFont().deriveFont(searchButton.getFont().getSize()+5f));
        searchButton.setText("🔍");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        jLabel5.setText("Ort:");

        coordinatesButton.setText("Namen zuordnen");
        coordinatesButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                coordinatesButtonItemStateChanged(evt);
            }
        });

        jLabel6.setText("Datum (Tag oder Jahr):");

        jLabel7.setText("Anlass:");

        jLabel8.setText("Personen:");

        openPictureButton.setText("Bild öffnen");
        openPictureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openPictureButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout searchTabLayout = new javax.swing.GroupLayout(searchTab);
        searchTab.setLayout(searchTabLayout);
        searchTabLayout.setHorizontalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(placeSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reasonSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personsSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(searchTabLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchTabLayout.createSequentialGroup()
                                .addComponent(readyPictureDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(searchTabLayout.createSequentialGroup()
                                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane8)
                                    .addComponent(jScrollPane4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coordinatesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(searchTabLayout.createSequentialGroup()
                                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(searchTabLayout.createSequentialGroup()
                                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(forwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(openPictureButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap())))))))
        );
        searchTabLayout.setVerticalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchTabLayout.createSequentialGroup()
                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reasonSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personsSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(searchTabLayout.createSequentialGroup()
                        .addComponent(readyPictureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openPictureButton))
                        .addGap(8, 8, 8)
                        .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchTabLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchTabLayout.createSequentialGroup()
                                .addComponent(coordinatesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(forwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        tabWindow.addTab("Suche", searchTab);

        rawPicturesList.setModel(new ArrayListModel<>(arch.getRawPictures()));
        rawPicturesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rawPicturesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                rawPicturesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(rawPicturesList);

        saveButton.setFont(saveButton.getFont().deriveFont(saveButton.getFont().getSize()+25f));
        saveButton.setText("✓");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Ort:");

        jLabel2.setText("Datum:");

        jLabel3.setText("Personen(+):");

        jLabel4.setText("Anlass:");

        openFolderButton.setText("Ordner öffnen");
        openFolderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openFolderButtonMouseClicked(evt);
            }
        });

        rawPictureDisplayLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rawPictureDisplayLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editTabLayout = new javax.swing.GroupLayout(editTab);
        editTab.setLayout(editTabLayout);
        editTabLayout.setHorizontalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(openFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editTabLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(personsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(reasonTextField)
                            .addComponent(dateTextField)
                            .addComponent(placeTextField))
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(rawPictureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        editTabLayout.setVerticalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editTabLayout.createSequentialGroup()
                        .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(editTabLayout.createSequentialGroup()
                                .addComponent(rawPictureDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(placeTextField)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openFolderButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editTabLayout.createSequentialGroup()
                                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(personsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))))
                    .addGroup(editTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );

        tabWindow.addTab("Bearbeitung", editTab);

        jLabel9.setText("Ordner:");

        jLabel10.setText("Zeit-Format:");

        jLabel11.setText("Ordner fertig:");

        jLabel12.setText("Ordner zu erledigen:");

        saveSettings.setText("Speichern");
        saveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettingsActionPerformed(evt);
            }
        });

        folderSetting.setText(Archivar.PREFS.get("folder", System.getProperty("user.home") + File.separator + "Archivar"));

        folderReadySetting.setText(Archivar.PREFS.get("folder-ready", "bearbeitet"));

        folderRawSetting.setText(Archivar.PREFS.get("folder-raw", "unbeschriftet"));

        formatSetting.setText(Archivar.PREFS.get("format", "dd.MM.yyyy"));

        jLabel13.setText("Farbe:");

        colorSetting.setText(Archivar.PREFS.get("color", "#FF000"));

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveSettings))
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(58, 58, 58)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(folderSetting, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                            .addComponent(folderReadySetting)
                            .addComponent(folderRawSetting)
                            .addComponent(formatSetting)
                            .addComponent(colorSetting))))
                .addContainerGap())
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(settingsPanelLayout.createSequentialGroup()
                                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(folderSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12))
                                    .addGroup(settingsPanelLayout.createSequentialGroup()
                                        .addComponent(folderReadySetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(folderRawSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addComponent(formatSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(colorSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                .addComponent(saveSettings)
                .addContainerGap())
        );

        tabWindow.addTab("Einstellungen", settingsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabWindow)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabWindow)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void readyPicturesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_readyPicturesListValueChanged
        Picture pic = readyPicturesList.getSelectedValue();
        if (pic == null) return;
        placeResultText.setText(pic.place);
        if (pic.date.getTime() == 0) {
            dateResultText.setText("");
        } else {
            dateResultText.setText(Picture.FORMAT.format(pic.date));
        }
        reasonResultText.setText(pic.reason);
        personsResultText.setText(pic.listPersons());
        
        Image image = pic.getImage();
        Dimension d = arch.calculateSize(image.getHeight(null), image.getWidth(null), readyPictureDisplayLabel.getHeight(), readyPictureDisplayLabel.getWidth());
        
        Image img = arch.scaleImage(d, image);
        if (coordinatesButton.isSelected()) {
            readyPicturesList.getSelectedValue().drawCoordinates(img, d);
        }
        readyPictureDisplayLabel.setIcon(new ImageIcon(img));
        readyImage = img;
        readyDimension = d;
    }//GEN-LAST:event_readyPicturesListValueChanged

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        int i = readyPicturesList.getSelectedIndex();
        if (i > 0) {
            readyPicturesList.setSelectedIndex(i - 1);
        }
    }//GEN-LAST:event_backButtonMouseClicked

    private void forwardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forwardButtonMouseClicked
        int i = readyPicturesList.getSelectedIndex();
        if (i < arch.getRawPictures().size()) {
            readyPicturesList.setSelectedIndex(i + 1);
        }
    }//GEN-LAST:event_forwardButtonMouseClicked

    private void openFolderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openFolderButtonMouseClicked
        try {
            Desktop.getDesktop().open(new File(Picture.FOLDER_REMAINING));
        } catch (IOException ex) {
            Logger.getLogger(SearchEditWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_openFolderButtonMouseClicked

    private void openPictureButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openPictureButtonMouseClicked
        try {
            Desktop.getDesktop().open(new File(readyPicturesList.getSelectedValue().getPath()));
        } catch (IOException ex) {
            Logger.getLogger(SearchEditWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_openPictureButtonMouseClicked

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        Picture pic = rawPicturesList.getSelectedValue();
        pic.insertData(placeTextField.getText(), reasonTextField.getText(), personsTextField.getText(), dateTextField.getText());
        pic.save(arch.getConnection());
        arch.getRawPictures().remove(pic);
        placeTextField.setText("");
        reasonTextField.setText("");
        personsTextField.setText("");
        dateTextField.setText("");
        rawPicturesList.updateUI();
        this.rawPicturesListValueChanged(null);
        arch.getReadyPictures().add(pic);
        if (!activeSearch) {
            readyPicturesList.updateUI();
            this.readyPicturesListValueChanged(null);
        }
    }//GEN-LAST:event_saveButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        List<Picture> search = arch.search(placeSearchField.getText(), dateSearchField.getText(), reasonSearchField.getText(), personsSearchField.getText());
        readyPicturesList.setModel(new ArrayListModel<>(search));
        readyPicturesList.setSelectedIndex(0);
        activeSearch = search != arch.getReadyPictures();
    }//GEN-LAST:event_searchButtonMouseClicked

    private void coordinatesButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coordinatesButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            readyPictureDisplayLabel.setIcon(new ImageIcon(arch.scaleImage(readyDimension, readyPicturesList.getSelectedValue().getImage())));
            return;
        }
        readyPicturesList.getSelectedValue().drawCoordinates(readyImage, readyDimension);
        readyPictureDisplayLabel.setIcon(new ImageIcon(readyImage));
    }//GEN-LAST:event_coordinatesButtonItemStateChanged

    private void rawPicturesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_rawPicturesListValueChanged
        Picture pic = rawPicturesList.getSelectedValue();
        Image image = pic.getImage();
        Dimension d = arch.calculateSize(image.getHeight(null), image.getWidth(null), rawPictureDisplayLabel.getHeight(), rawPictureDisplayLabel.getWidth());
        
        Image img = arch.scaleImage(d, image);
        rawPictureDisplayLabel.setIcon(new ImageIcon(img));
        this.rawImage = img;
        this.rawDimension = d;
    }//GEN-LAST:event_rawPicturesListValueChanged

    private void saveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSettingsActionPerformed
        Archivar.PREFS.put("folder", folderSetting.getText());
        Archivar.PREFS.put("folder-ready", folderReadySetting.getText());
        Archivar.PREFS.put("folder-raw", folderRawSetting.getText());
        Archivar.PREFS.put("format", formatSetting.getText());
        Archivar.PREFS.put("color", colorSetting.getText());
        JOptionPane.showMessageDialog(null, "Bitte Programm neustarten, um Änderungen anzuwenden.");
    }//GEN-LAST:event_saveSettingsActionPerformed

    private void rawPictureDisplayLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawPictureDisplayLabelMouseClicked
        Graphics g = rawImage.getGraphics();
        int gap = 0;
        if (rawImage.getHeight(null) != rawPictureDisplayLabel.getHeight()) {
            gap = (rawPictureDisplayLabel.getHeight() - rawImage.getHeight(null)) / 2;
        }
        double percentX = (double)evt.getX() / rawDimension.width; // 0 = 0%; 1 = 100%
        double percentY = (double)(evt.getY() - gap) / rawDimension.height;
        
        RelativeCoordinate rc = new RelativeCoordinate(percentX, percentY);
        List<RelativeCoordinate> list = rawPicturesList.getSelectedValue().getCoordinates();
        list.add(rc);
        
        g.setColor(Picture.COLOR);
        g.drawString(Integer.toString(list.size()), (int) (percentX * rawDimension.width), (int) (percentY * rawDimension.height));
        g.dispose();
        rawPictureDisplayLabel.setIcon(new ImageIcon(rawImage));
    }//GEN-LAST:event_rawPictureDisplayLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        /*    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchEditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEditWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField colorSetting;
    private javax.swing.JCheckBox coordinatesButton;
    private javax.swing.JTextPane dateResultText;
    private javax.swing.JTextField dateSearchField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JPanel editTab;
    private javax.swing.JTextField folderRawSetting;
    private javax.swing.JTextField folderReadySetting;
    private javax.swing.JTextField folderSetting;
    private javax.swing.JTextField formatSetting;
    private javax.swing.JButton forwardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JButton openFolderButton;
    private javax.swing.JButton openPictureButton;
    private javax.swing.JTextPane personsResultText;
    private javax.swing.JTextField personsSearchField;
    private javax.swing.JTextField personsTextField;
    private javax.swing.JTextPane placeResultText;
    private javax.swing.JTextField placeSearchField;
    private javax.swing.JTextField placeTextField;
    private javax.swing.JLabel rawPictureDisplayLabel;
    private javax.swing.JList<Picture> rawPicturesList;
    private javax.swing.JLabel readyPictureDisplayLabel;
    private javax.swing.JList<Picture> readyPicturesList;
    private javax.swing.JTextPane reasonResultText;
    private javax.swing.JTextField reasonSearchField;
    private javax.swing.JTextField reasonTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveSettings;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchTab;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JTabbedPane tabWindow;
    // End of variables declaration//GEN-END:variables
}
